WWCodeTokyo/speak-her-db

web/src/components/CardHeader.vue
web/src/components/SpeakerCard.vue
web/src/components/TagBox.vue
web/src/components/hero/CallToAction.vue
web/src/main.js
web/src/styles/main.scss
web/src/views/FindSpeaker.vue

Speaker card tweaks

---

web/src/components/SpeakerCard.vue
web/src/components/nomination/LocationInput.vue
web/src/main.js
web/src/plugins/airtable.js
web/src/styles/main.scss
web/src/views/FindSpeaker.vue

Resolves https://github.com/WWCodeTokyo/speak-her-db/issues/34
Fetching prefectures on FindSpeaker and NominateSpeaker pages.
Find Speaker:
LocationInput:

Fetch prefectures from Airtable

---

web/.eslintrc.js
web/package.json
web/src/components/contact/ContactDialog.vue
web/src/main.js
web/yarn.lock

Part I of #43 
Add validation to the Contact Speaker form using vuelidate. Please review #41 first as this is currently branched off of that

43 form validation for Contact Speaker

---

web/src/components/nomination/NameInput.vue
web/src/components/nomination/NominateForm.vue
web/src/components/nomination/SubmitterInput.vue
web/src/components/nomination/TopicsInput.vue
web/src/components/nomination/UrlsInput.vue

Resolves #20 
**Form info**
**Request payload**
**Console output**
**Airtable database**

Submit speakers to airtable

---

web/src/views/FindSpeaker.vue

disable search bar for MVP

---

web/src/components/nomination/NominateForm.vue
web/src/components/nomination/UrlsInput.vue

validate urls

---

web/src/components/alerts/VariableAlert.vue
web/src/components/nomination/NominateForm.vue

alerts on the form

---

web/src/components/LocaleSwitcher.vue

Save locale in local storage... insert locale storage joke here ;)

persist locale

---

web/src/i18n/locales/en.json
web/src/i18n/locales/ja.json

Resolves #1
Used Lokalize.io to make a basic machine translation of the site. There are likely mistakes, so we should have a human look it over. I can ask for some volunteers in Women Who Code.

Basic Machine Translation

---

web/src/i18n/locales/ja.json

Thank you Mayu for helping me translate!

Add Mayu's translations

---

web/src/components/about/FAQ.vue
web/src/components/cards/PageCard.vue
web/src/i18n/locales/en.json
web/src/views/About.vue

About page

---

web/src/components/AppFooter.vue
web/src/i18n/locales/en.json
web/src/i18n/locales/ja.json

Resolves https://github.com/WWCodeTokyo/speak-her-db/issues/73
I tried to add the Netlify badge but it was too big and too hard to make it look good on the footer. So I went for a simple text link.

Add powered by netlify to footer

---

web/src/components/SpeakerCard.vue
web/src/components/TagBox.vue
web/src/plugins/airtable.js

Resolves #72 
Could use some help on this one figuring out the filter function.

Fix Tag fetching

---

web/src/components/CardHeader.vue
web/src/components/SpeakerCard.vue

I prioritized this one because it's a pretty basic info for someone to decide to contact a speaker.
Looks like this:
What do you think @ann-kilzer ?

Add languages to SpeakerCard

---

web/src/components/nomination/NominateForm.vue

Resolves https://github.com/WWCodeTokyo/speak-her-db/issues/82
Tested local and submitting to production db and it works 👍 
@ann-kilzer

[Bugfix] Include consent field on payload

---

web/src/i18n/locales/en.json
web/src/i18n/locales/ja.json

Resolves #25 
Contact address is now speakherjp@gmail.com

Update contact address for users who need to opt out or change data.

---

web/src/i18n/i18n.js

For more information, see the following link: 
https://blog.logrocket.com/advanced-localization-techniques-vue-js

auto-detect a user's preferred language

---

.github/workflows/unittest.yml

Resolves #52 
It works well in my testing.

Automate unit tests in GH actions

---

web/src/components/nomination/NominateForm.vue
web/src/components/nomination/PronounInput.vue
web/src/i18n/locales/en.json
web/src/plugins/airtable.js

Resolves #91 
- Allow users to submit pronouns, including custom strings for pronouns. 
- Keep it simple for the suggestions: "she/her", "they/them"
- Update the bio label to suggest writing in 3rd person to avoid the "I" content
I will figure out a good place to display pronouns in #92

Collect pronouns

---

web/src/plugins/airtable.js

Resolves #104 
I added prefecture codes to airtable, and now we can sort on that field.
@wakanapo Thanks for your suggestion. Feel free to take a look at the deploy-preview in the GH actions section below.

order by prefecture code

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md

- Update readme to remove references to JP database
- Update docs to switch contact email to just me

Update docs to remove references to JP team

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md

Reverts WWCodeTokyo/speak-her-db#169

Revert "Update docs to remove references to JP team"

---

web/src/components/Pagination.vue

References #181 
*Please link to the related issue, using the [references] keyword only if the PR completes the entire issue*
Experiment if fixing the eslint issues resolves the Netlify ESLint indeterminate status.
Address ESLint warning -- I turned it off for the whole file instead of line by line because I need to protect the HTML, it was tricky to do it line by line. 
If this works correctly, all the checks should pass.

fix linter error

---

.github/workflows/main.yml

Trying out this [Lighthouse](https://developers.google.com/web/tools/lighthouse/) GitHub Action check, modeled after this example: https://github.com/jakejarvis/lighthouse-action
We'll have to merge it to master to see 🧐

Add Lighthouse Check Github Action

---

web/src/components/nomination/LanguageInput.vue
web/src/components/speaker/Languages.vue
web/src/util/format.js

Resolves #176 
- Remove native language
- Remove `util` folder (added by me). Recently a code quality expert suggested that such folders become the "junk drawer of a repository."
View the Speaker Cards:
View the nomination form:

remove native language from UI

---

web/src/components/nomination/JobInput.vue
web/src/components/nomination/NominateForm.vue
web/src/components/nomination/PronounInput.vue
web/src/components/nomination/SecondaryAffiliationInput.vue
web/src/i18n/locales/en.json
web/src/i18n/locales/ja.json

Resolves #122 
Added maximum character length to the following fields:
- Name (150 characters)
- Job Title (200 characters)
- Company (200 characters)
- Secondary Title (200 characters)
- Secondary Affiliation (200 characters)
- pronouns (50 characters)
Input text above the required max length to each of the form field and click outside of the field

Add maximum character length to form fields

---

README.md
web/cypress.config.js
web/cypress/e2e/about.cy.js
web/cypress/e2e/home.cy.js
web/cypress/e2e/nominate.cy.js
web/cypress/fixtures/example.json
web/cypress/support/commands.js
web/cypress/support/e2e.js
web/package.json
web/yarn.lock

Resolves #300 
Basic cypress setup and skeleton tests
See steps in readme for how to run cypress. Note you'll need to run `yarn install` first

300 add cypress

---

LICENSE

Update-year
Updating 2020 year to 2022

2020 > 2022

---

web/src/i18n/locales/en.json

Updated the year to the current year.

Update 2020 > 2022
