WWCodeTokyo/speak-her-db

- web/src/App.vue
- web/src/components/Sidebar.vue
- web/src/components/Toolbar.vue
- Add in a sidebar for mobile devices (xs and s breakpoints)
- Be able to toggle the sidebar with a 🍔 hamburger menu, and dismiss by clicking off the sidebar
- DRY up the navigation between the sidebar and top bar
- Add the locale switcher to the sidebar (future styling may happen after @yanarchy lands her changes)
> 29 responsive sidebar

- web/src/App.vue
- web/src/components/AppFooter.vue
- web/src/components/about/Summary.vue
- web/src/components/hero/CallToAction.vue
- web/src/views/FindSpeaker.vue
- web/src/views/Home.vue
Resolves #37 
- Makes the home page a nice vertical scroll, inspired by #39. Add a brief summary section. 
- Make the navigation scroll down rather than navigate to a separate page
- Add a footer as a placeholder
> 37 landing page tweaks

- web/src/components/LocaleSwitcher.vue
I was a bit confused when I saw the site in Japanese and the language switch was showing `日本語` instead of `English`.
If someone can't read Japanese, they won't know they should click the 日本語 button to change it to English, so I think it makes more sense that the button show the language to switch to, instead of the current language.
It's a suggestion, let me know what you think!
> [Suggestion] Locale switch button show opposing language

- web/src/components/nomination/NominateForm.vue
- web/src/components/nomination/TopicsInput.vue
- web/src/i18n/locales/en.json
- web/src/i18n/locales/ja.json
Branched out of #76 , finishes resolving #71 
- Changed `v-autocomplete` to [`v-combobox`](https://vuetifyjs.com/en/components/combobox/) to allow entering new items
- Existing items are sent as an `id` to Airtable, to make the link with the existing Topic record, new items are sent as the typed strings, to create new records with the string as the name (`name_en`)
- The magic works because the Airtable call has a parameter `typecast: true`, that makes the best effort to identify the operation (if it's an existing id, link the record, if it's not, create a new record and then link it)
- Added a small parsing logic on the payload function to make this work
**Specs:**
**Limitations:**
- Cannot translate the topic name in English and Japanese, because the new values are just one simple …
> Add new topic from dropdown

- web/src/components/nomination/NominateForm.vue
- web/src/components/nomination/TopicsInput.vue
- web/src/i18n/locales/en.json
- web/src/i18n/locales/ja.json
- web/src/plugins/airtable.js
Pre-requirement to resolve #71 
Topics are now in a separate table (named `Topics`, [access with your Airtable account here](https://airtable.com/tblllBktP0o2lNo8y/viwN4bSK6NEvx0PjW?blocks=hide)), where we can set the name in any language and add new topics anytime.
The nomination form now fetches the topics from this table and the speaker entry `has many` topics (it's a many to many relation now)
*Specs*
- ~~[x] We can translate the topic names in the database, on the column `name_ja`~~
> Fetch topics from Airtable

- web/src/plugins/airtable.js
- web/src/views/FindSpeaker.vue
Part 1 of #86 
Sort speakers from A-Z by `name_en`.
In the future we could allow different types of sorting.
> 86 sort speakers

- web/src/components/TagBox.vue
Part of #101 
Quick hack to fix tag wrapping for both mobile and speakers with many tags.
We can address the language placement in another PR, perhaps alongside #92
> Add some vertical space to the tags so they wrap nicely

- web/src/components/CardHeader.vue
- web/src/components/SpeakerCard.vue
- web/src/components/nomination/LanguageInput.vue
- web/src/components/nomination/NominateForm.vue
- web/src/util/format.js
- web/src/views/FindSpeaker.vue
Part 2 of #88
Make sure we're getting language information from the new relation model.
Note when I deploy this to prod, I will need to have a small window of downtime to replace `languages2` with `languages`. I will save the `languages` as `legacy_languages` until we agree this is successful.
Will try to do this around midnight if approved.
> read updated table for speaker card

- web/src/components/TagBox.vue
Just a small tweak to improve the tag color generation, so there are fewer duplicates. Also use caching since the computation is more expensive.
Before:
After:
> better color generation, including caching

- web/package.json
- web/public/index.html
- web/src/main.js
- web/yarn.lock
It would be better using Google Fonts rather than roboto-fontface.
In this case, roboto-fontface has shortcomings:
- not supporting "font-display: swap"
- lack of Netlify's CDN nodes in Japan
- wasting bandwidth of Netlify's free tier
FYI
https://community.netlify.com/t/slow-avg-page-load-time-from-japan/495/2
> use Google Fonts

- .gitignore
- README.md
- web/.env.sample
- web/src/components/nomination/NominateForm.vue
References https://github.com/WWCodeTokyo/speak-her-db/issues/137
Add a Development database to allow anyone to develop safely without access to production database.
**Description of changes in this PR**
- Created a [Dev database on Airtable](https://github.com/WWCodeTokyo/speak-her-db/issues/137#issuecomment-692689209)
- Added instructions on readme on how to setup access to the dev database
- `NODE_ENV=development` will use the dev database, `NODE_ENV=production` will use the production database
- Removed the "dry run" on the submission form for development mode (now it actually saves to the database even in dev mode)
- Pull this branch on your local environment
- Setup `.env.development` according to README instructions
- Run `yarn serve` and check …
> Setup development database

- web/src/components/contact/ContactDialog.vue
- web/src/components/contact/ContactResult.vue
- web/src/views/FindSpeaker.vue
Solves https://github.com/WWCodeTokyo/speak-her-db/issues/135
- Fix the reference for speaker name on the contact form submission
- Also tweaked it to show the speaker name according to the selected locale (Japanese or English)
Production:
- Submit the contact speaker form on the [deploy-preview](https://deploy-preview-147--speak-her-db.netlify.app/) and check [Netlify form submission](https://app.netlify.com/sites/speak-her-db/forms/5ef8717c5e762a00084c9758#item-5f4d9a3fa58b9e2b27fe476b) to see that `Speaker` is now correct (no longer `undefined`).
- Change the locale (JA<>EN) and try the contact form again, check that the speaker name changes according to the selected language (submission to Netlify remains in English, to make it easier for us)
Local:
- Pull this branch and run the app …
> Fix speaker name on ContactDialog and submission payload

- web/src/components/nomination/NominateForm.vue
Issue #150 
Minor change: hint to persistent-hint, so the hint is not only visible when the field is in focus, but when the form is loaded
Changed hint to persistent-hint to improve consistency of form submissions
Load the page, check if the hint below the speaker bio is visible
> Bios persistent hint

- web/src/components/Pagination.vue
- web/src/views/FindSpeaker.vue
Resolves #168
Adds a loading spinner on the top page until we fetched the spinners from the database.
- Adds the vuetify `progress-circular` component as a loading spinner on the top page until the speakers are fetched from the db
*How do the reviewers QA this? Feel free to write unit tests or describe manual testing steps here*
- Access start page and scroll down
- If results are already loaded you might have to refresh depending on how fast results are loading for you
- One option to slow the db fetch down might be to simulate a slow mobile network via the chrome browser and clear the browser cache so the loading spinner shows for a longer time.
> feat: adds loading spinner for start page

- web/src/components/nomination/TopicsInput.vue
- web/src/components/speaker/CardFooter.vue
- web/src/components/speaker/TagBox.vue
- web/src/views/FindSpeaker.vue
Resolves #154 
*Please link to the related issue, using the [references] keyword only if the PR completes the entire issue*
Better Support for Topics in Japanese language
1) Browse through the speakers and verify that tags appear. Toggle locale to Japanese and ensure that most tags appear in Japanese, and some fall back to English where translations are absent.
2) Nominate a speaker. Add some existing tags using
a)  the checkbox.
b) type completion
c) a custom submission by typing into the input.
> Bilingual Tag Display

- web/src/components/nomination/NominateForm.vue
- web/src/i18n/locales/ja.json
Resolves #178
Make the Japanese name on nomination form optional. 
- Go to the nomination form, register yourself without a Japanese name
- Go to airtable and check the published flag
- Switch to Japanese language
- Check the top page, the English name should be used
- Click on the contact speaker button, the contact form should use the English name
> Make Japanese name optional on nomination form

- web/src/components/nomination/JobInput.vue
- web/src/components/nomination/SecondaryAffiliationInput.vue
- web/src/i18n/locales/en.json
- web/src/i18n/locales/ja.json
Resolves #192 
Various fixes around Primary and secondary job
- Neaten up i18n file structure
- Add a hint to job input
- Use persistent-hint
- View the netlify build
- Check i18n and fallback by toggling between Japanese and English Input
> organize job / secondary affiliation i18n fields, add persistent hint

- web/src/i18n/locales/ja.json
Resolves #212
As we discussed, I translated "Press Coverage" as my first issue.
I translate "Press Coverage" to Japanese "掲載メディア".
It is a common expression to indicate what kind of media broadcast us.
I tested in my local environment.
> #212 translate press coverage

- web/src/i18n/locales/ja.json
Resolves #[Issue number] 
*Please link to the related issue, using the [Resolves] keyword only if the PR completes the entire issue*
I translated the find speaker part. This is also related #193 issue.
She/her and he/him are not 第一人称 it is 第三人称(it means the name is called from the third person). I felt It sounds a very technical expression, not appropriate for an individual profile.
Then I put 呼称. It includes a nickname, pronouns, any name. At least it sounds like "This is how to call them without calling the real name". When I find more appropriate words, I would like to update.
Translating the find speaker part.
I translated that part. 
*How do the reviewers QA this? Feel free to write unit tests or describe …
> Translate find speaker

- server/Gemfile
- server/Gemfile.lock
- server/README.md
- server/app/controllers/application_controller.rb
- server/app/controllers/languages_controller.rb
- server/app/controllers/locations_controller.rb
- server/app/controllers/spoken_languages_controller.rb
- server/app/controllers/topics_controller.rb
- server/app/models/speaker.rb
- server/app/models/spoken_language.rb
- server/app/views/locations/index.json.jbuilder
- server/app/views/spoken_languages/index.json.jbuilder
- server/app/views/topics/index.json.jbuilder
- server/config/routes.rb
- server/db/migrate/20210220073616_change_language_to_spoken_language.rb
- server/db/migrate/20210220073757_change_speaker_language_to_speaker_spoken_language.rb
- server/db/schema.rb
- server/db/seeds.rb
- server/lib/tasks/mock_data.rake
- server/test/controllers/languages_controller_test.rb
- server/test/controllers/location_controller_test.rb
- server/test/controllers/locations_controller_test.rb
- server/test/controllers/spoken_languages_controller_test.rb
- server/test/controllers/topics_controller_test.rb
- server/test/fixtures/locations.yml
- server/test/fixtures/speakers.yml
- server/test/fixtures/spoken_languages.yml
- server/test/fixtures/topics.yml
- server/test/models/spoken_language_test.rb
**Issue: https://github.com/WWCodeTokyo/speak-her-db/issues/224**
**This is a sub-PR to merged to #210 Rails Backend.**
This PR implements the following changes:
- Adds the fetch/index endpoint to all the core models (Topics, Languages and Locations)
- Refactors the model `Language` and its API endpoint to `SpokenLanguage` to avoid conflicts with Rails internationalization (`language` seems to be a reserved word)
- Add a simple logic for the root `/` path to show the available API routes if you access the server on your browser in development mode. If it's not development mode, it will redirect to the production site (https://speakher.jp)
- Fix and implement tests for the API endpoints
Current available endpoints:
```
GET / (root)          => redirects to production site or shows the API …
```
> (Sub-PR) Add endpoints to fetch resources (Topics, Languages and Locations)

- web/package.json
- web/patches/node-fetch+2.6.7.patch
- web/vue.config.js
- web/webpack.functions.js
- web/yarn.lock
The node-fetch 2.6.7 does not seems to be compatible with NodeJS [Abort Controller](https://developer.mozilla.org/en-US/docs/Web/API/AbortController). It broke the lambda function. 
Add a patch for the library for now. 
sample error message:
`TypeError - Expected signal to be an instanceof AbortSignal`
Resolves #262
This disable the mangle options of the webpack uglify plugin. 
*How do the reviewers QA this? Feel free to write unit tests or describe manual testing steps here*
- Go to https://deploy-preview-278--speak-her-db.netlify.app/
- Click on "Find a speaker"
- see the tags
- :tada:
> Fix netlify lambda functions
